# Changes here will be overwritten by Copier
_commit: 5.4.0
_src_path: https://github.com/DiamondLightSource/python-copier-template.git
author_email: tim.burd@diamond.ac.uk
author_name: Timothy Burd
component_lifecycle: experimental
component_owner: group:default/personnel-safety-systems
component_type: service
description: Module to trigger a phone call when certain alarms are raised
distribution_name: pssAutoDial
docker: true
docs_type: README
git_platform: github.com
github_org: DiamondLightSource
package_name: pssAutoDial
pypi: false
repo_name: pssAutoDial
strict_typing: false
type_checker: pyright
