apiVersion: apps/v1
kind: Deployment
metadata:
  name: pss-autodial
spec:
  selector:
    matchLabels:
      app: pss-autodial
  replicas: 1
  template:
    metadata:
      labels:
        app: pss-autodial
    spec:
      containers:
      - name: pss-autodial
        image: ghcr.io/diamondlightsource/pssautodial:latest
        command: ["pss_autodial"]
        resources:
          limits:
            cpu: "1"
            memory: 300M
        ports:
        - containerPort: 80
        env:
        - name: EPICS_CA_NAME_SERVERS
          value: 172.23.240.13
        - name: EPICS_CA_AUTO_ADDR_LIST
          value: NO
        - name: ACCOUNT_SID
          valueFrom:
            secretKeyRef:
                name: credentials-sealedsecret
                key: ACCOUNT_SID
        - name: AUTH_TOKEN
          valueFrom:
            secretKeyRef:
                name: credentials-sealedsecret
                key: AUTH_TOKEN
        - name: TWILIO_NUMBER
          valueFrom:
            secretKeyRef:
                name: credentials-sealedsecret
                key: TWILIO_NUMBER
        - name: TO_NUMBER
          valueFrom:
            secretKeyRef:
                name: credentials-sealedsecret
                key: TO_NUMBER
