apiVersion: v1
kind: Service
metadata:
  name: pss-autodial # example service name that the ingress will target
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: pss-autodial
  type: ClusterIP
